# Generated by Django 2.1.6 on 2019-02-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, upload_to='content/file/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='content/image/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
