# Generated by Django 2.1.6 on 2019-04-11 20:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
