# Generated by Django 2.1.6 on 2019-04-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190411_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='source',
        ),
    ]
