# Generated by Django 2.1.6 on 2019-04-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_module_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='file',
        ),
    ]
