# Generated by Django 2.1.6 on 2019-02-15 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_content_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=300)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='content_note', to='course.Content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_note', to='course.Course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='module_note', to='course.Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
