# Generated by Django 2.1.6 on 2019-04-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takencourse',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='takenmodule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
