# Generated by Django 2.1.6 on 2019-02-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_contentnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnote',
            name='content',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='content_note', to='course.Content'),
        ),
        migrations.AlterField(
            model_name='contentnote',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_note', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='contentnote',
            name='module',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='module_note', to='course.Module'),
        ),
    ]
