# Generated by Django 2.1.6 on 2019-02-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190215_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnote',
            name='course',
        ),
    ]
