# Generated by Django 2.1.6 on 2019-02-15 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_contentnote_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnote',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_note', to=settings.AUTH_USER_MODEL),
        ),
    ]
