# Generated by Django 2.1.6 on 2019-02-15 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20190215_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnote',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='content_note', to='course.Content'),
        ),
        migrations.AlterField(
            model_name='contentnote',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='module_note', to='course.Module'),
        ),
        migrations.AlterField(
            model_name='contentnote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_note', to=settings.AUTH_USER_MODEL),
        ),
    ]
