# Generated by Django 2.1.6 on 2019-02-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190214_1133'),
        ('course', '0008_auto_20190215_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(null=True, related_name='students_enrolled', to='accounts.Student'),
        ),
    ]
