# Generated by Django 2.1.6 on 2019-02-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190214_1133'),
        ('course', '0010_takencourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_taken', to='course.Module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_module', to='accounts.Student')),
            ],
        ),
    ]
