# Generated by Django 2.1.6 on 2019-02-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190214_1133'),
        ('course', '0011_takenmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_taken', to='course.Content')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_content', to='accounts.Student')),
            ],
        ),
    ]
