# Generated by Django 2.1.6 on 2019-02-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190223_1139'),
        ('course', '0012_takencontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_completed_by_student', to='course.Module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_completed', to='accounts.Student')),
            ],
        ),
    ]
