# Generated by Django 2.1.6 on 2019-02-25 21:55

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_completedmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=colorful.fields.RGBColorField(default='#007bff'),
        ),
        migrations.AddField(
            model_name='subject',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
