# Generated by Django 2.1.6 on 2019-02-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20190225_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
