# Generated by Django 2.1.6 on 2019-02-27 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20190225_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedmodule',
            name='module',
        ),
        migrations.RemoveField(
            model_name='completedmodule',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='takencontent',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content_module_taken', to='course.Module'),
        ),
        migrations.AddField(
            model_name='takencourse',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='takenmodule',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='takenmodule',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='module_course_taken', to='course.Course'),
        ),
        migrations.DeleteModel(
            name='CompletedModule',
        ),
    ]
