# Generated by Django 2.1.6 on 2019-02-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20190227_2248'),
        ('course', '0017_auto_20190228_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='tag_courses', to='accounts.Tag'),
        ),
    ]
