# Generated by Django 2.1.6 on 2019-02-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20190228_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenmodule',
            name='source',
            field=models.URLField(default=None),
        ),
    ]
