# Generated by Django 2.1.6 on 2019-02-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20190228_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenmodule',
            name='source',
        ),
        migrations.AddField(
            model_name='module',
            name='source',
            field=models.URLField(default=None),
        ),
    ]
