# Generated by Django 2.1.6 on 2019-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20190228_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='source',
            field=models.URLField(blank=True, default=None),
        ),
    ]
