# Generated by Django 2.1.6 on 2019-02-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20190228_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnote',
            name='module',
        ),
    ]
