# Generated by Django 2.1.6 on 2019-03-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_remove_contentnote_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
