# Generated by Django 2.1.6 on 2019-03-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_auto_20190309_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
