# Generated by Django 2.1.6 on 2019-03-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_auto_20190313_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
