# Generated by Django 2.1.6 on 2019-03-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_auto_20190322_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateField(auto_now_add=True, unique_for_date=True),
        ),
    ]
