# Generated by Django 2.1.6 on 2019-03-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.TextField(max_length=500)),
                ('code_content', models.TextField(max_length=500)),
                ('lang', models.TextField(max_length=500)),
                ('code_input', models.TextField(max_length=500)),
                ('compile_status', models.TextField(max_length=500)),
                ('run_status_status', models.TextField(max_length=500)),
                ('run_status_time', models.TextField(max_length=500)),
                ('run_status_memory', models.TextField(max_length=500)),
                ('run_status_output', models.TextField(max_length=500)),
                ('run_status_stderr', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
