# Generated by Django 2.1.6 on 2019-04-08 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_bio'),
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='OtherCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ide.Code')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ide.SupportedLanguages')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(0, 'up'), (1, 'down')], null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ide.Code')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='WebCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.TextField(max_length=500)),
                ('js', models.TextField(max_length=500)),
                ('html', models.TextField(max_length=500)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ide.Code')),
            ],
        ),
        migrations.DeleteModel(
            name='codes',
        ),
    ]
