# Generated by Django 2.1.6 on 2019-04-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0003_auto_20190410_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
