# Generated by Django 2.1.6 on 2019-04-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0005_auto_20190411_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='code',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
