# Generated by Django 2.1.6 on 2019-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0009_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
