# Generated by Django 2.1.6 on 2019-05-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0010_auto_20190502_1342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('code', 'vote')},
        ),
    ]
