# Generated by Django 2.1.6 on 2019-05-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0011_auto_20190506_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
    ]
