# Generated by Django 2.1.6 on 2019-05-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190514_0207'),
        ('ide', '0012_auto_20190512_0126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('code', 'owner')},
        ),
    ]
