# Generated by Django 2.1.6 on 2019-03-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedstage',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='completedstage',
            name='last_entr',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
