# Generated by Django 2.1.6 on 2019-02-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exp',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_students', to='accounts.Tag'),
        ),
    ]
