# Generated by Django 2.1.6 on 2019-03-31 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190329_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='accounts.StudentLevel'),
        ),
    ]
