# Generated by Django 2.1.6 on 2019-02-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190212_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='default-96.png', upload_to='media/profile_pic/'),
        ),
    ]
