# Generated by Django 2.1.6 on 2019-05-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='point_required',
            new_name='point',
        ),
        migrations.RemoveField(
            model_name='takenbadge',
            name='score',
        ),
    ]
