# Generated by Django 2.1.6 on 2019-02-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190213_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='default-96.png', upload_to='profile_pic/'),
        ),
    ]
