# Generated by Django 2.1.6 on 2019-02-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190213_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='default-96.png', upload_to='learno/media/profile_pic/'),
        ),
    ]
