# Generated by Django 2.1.6 on 2019-02-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190214_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions_number',
        ),
    ]
