# Generated by Django 2.1.6 on 2019-02-17 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190217_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='takenbadge',
            name='quiz',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Question'),
        ),
        migrations.AddField(
            model_name='takenbadge',
            name='badge',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='taken_badges', to='accounts.Badge'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='last_entr',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
