# Generated by Django 2.1.6 on 2019-02-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190219_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Question'),
        ),
    ]
