# Generated by Django 2.1.6 on 2019-02-20 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190219_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_quiz', to='accounts.Quiz'),
        ),
    ]
