# Generated by Django 2.1.6 on 2019-02-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_studentanswer_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default-96.png', upload_to='learno/media/profile_pic/'),
        ),
    ]
