# Generated by Django 2.1.6 on 2019-02-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190223_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default-96.png', upload_to='profile_pic/'),
        ),
    ]
