# Generated by Django 2.1.6 on 2019-02-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20190223_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default-96.png', upload_to='picture_profile/'),
        ),
    ]
