# Generated by Django 2.1.6 on 2019-02-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190223_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='default-96.png', upload_to='picture_profile/'),
        ),
    ]
