# Generated by Django 2.1.6 on 2019-02-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20190224_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='quiz',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_stage', to='accounts.Stage'),
        ),
        migrations.AlterField(
            model_name='question',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questiones', to='accounts.Stage'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_answers', to='accounts.Student'),
        ),
    ]
