# Generated by Django 2.1.6 on 2019-02-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20190224_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastStudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Question')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_question_stage', to='accounts.Stage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_last_answers', to='accounts.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='completedstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stages', to='accounts.Stage'),
        ),
    ]
