# Generated by Django 2.1.6 on 2019-02-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20190224_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='laststudentanswer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='laststudentanswer',
            name='last_entr',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
