# Generated by Django 2.1.6 on 2019-02-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20190224_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exp',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=1),
        ),
    ]
