# Generated by Django 2.1.6 on 2019-02-25 22:10

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20190225_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorful.fields.RGBColorField(default='#007bff')),
                ('required_exp', models.PositiveIntegerField(blank=True, db_index=True, default=1)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.StageLevel'),
        ),
    ]
