# Generated by Django 2.1.6 on 2019-02-25 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20190225_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Novice'), (2, 'Apprentice'), (3, 'Trainee'), (4, 'Beginner'), (5, 'Amateur '), (6, 'Professional'), (7, 'Master'), (8, 'Wizard '), (9, 'Mage'), (10, 'White Mage'), (11, 'Regent'), (1, 'King')], default=1, max_length=30)),
                ('logo', models.ImageField(blank=True, default='', upload_to='level_pic/')),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AddField(
            model_name='stagelevel',
            name='text',
            field=models.IntegerField(choices=[(1, 'beginner'), (2, 'easy'), (3, 'normal'), (4, 'hard'), (5, 'very hard')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='accounts.StudentLevel'),
        ),
    ]
