# Generated by Django 2.1.6 on 2019-02-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20190226_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedstage',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_quizze', to='accounts.Quiz'),
        ),
    ]
