# Generated by Django 2.1.6 on 2019-02-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_completedstage_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquiz',
            name='score',
        ),
    ]
