# Generated by Django 2.1.6 on 2019-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_takenquiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
