# Generated by Django 2.1.6 on 2019-02-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_student_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_logo/'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
