# Generated by Django 2.1.6 on 2019-03-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20190227_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlevel',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='level_pic/'),
        ),
    ]
