# Generated by Django 2.1.6 on 2019-03-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20190301_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='position',
            new_name='level',
        ),
    ]
