# Generated by Django 2.1.6 on 2019-03-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20190309_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlevel',
            name='exp_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentlevel',
            name='graduation_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
