# Generated by Django 2.1.6 on 2019-03-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_supportedlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedlanguage',
            name='file',
            field=models.FileField(null=True, upload_to='supported_language_file/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='supportedlanguage',
            name='logo',
            field=models.ImageField(upload_to='supported_language_logo/'),
        ),
    ]
