# Generated by Django 2.1.6 on 2019-03-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20190317_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportedLanguage',
        ),
    ]
